sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm run test -- --coverage

after_success:
  - docker build -t multi-client ./client
  - docker build -t multi-nginx ./nginx
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker

  # login docker cli
  - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
  - docker push multi-client
  - docker push multi-nginx
  - docker push multi-server
  - docker push multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: "ap-southeast-1"
#   app: "docker-react"
#   env: "Dockerreact-env"
#   bucket_name: "elasticbeanstalk-ap-southeast-1-060542311733"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   serect_access_key: $AWS_SERECT_KEY
